// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DaeYzPDLgKO9YA59ZZKiAm5Y1pWOKq4',
    appId: '1:856058209559:android:a1e5225494a0bdfbd3c352',
    messagingSenderId: '856058209559',
    projectId: 'auth-app-2102',
    storageBucket: 'auth-app-2102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFMaKwY1LX513OUwiqPimmhAKqlDHRy4',
    appId: '1:856058209559:ios:43bb59d7ef24c655d3c352',
    messagingSenderId: '856058209559',
    projectId: 'auth-app-2102',
    storageBucket: 'auth-app-2102.appspot.com',
    iosClientId: '856058209559-au3tp0rpdafiigupfsknnqerecsj4nrn.apps.googleusercontent.com',
    iosBundleId: 'com.yuri.auth-app',
  );
}
